import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'services/auth_service.dart';
import 'screens/welcome_screen.dart';
import 'screens/home_screen.dart';
// import 'firebase_options.dart'; // This will be generated by the user

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  // We expect the user to have generated firebase_options.dart or configured it manually
  // For now, we'll try to initialize default, but if it fails, we might need options.
  // Since I cannot run flutterfire configure, I will assume the user will handle the config
  // or I should provide a way to handle it.
  // However, standard practice is `await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);`
  // But I don't have that file yet.
  // I will use a try-catch block or just Firebase.initializeApp() and let the user know.
  
  await Firebase.initializeApp();
  
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        Provider<AuthService>(
          create: (_) => AuthService(),
        ),
      ],
      child: MaterialApp(
        title: 'Flutter Auth Demo',
        theme: ThemeData(
          primarySwatch: Colors.blue,
          useMaterial3: true,
        ),
        home: const AuthWrapper(),
      ),
    );
  }
}

class AuthWrapper extends StatelessWidget {
  const AuthWrapper({super.key});

  @override
  Widget build(BuildContext context) {
    final authService = context.watch<AuthService>();
    return StreamBuilder<User?>(
      stream: authService.authStateChanges,
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.active) {
          final User? user = snapshot.data;
          return user == null ? const WelcomeScreen() : const HomeScreen();
        }
        return const Scaffold(
          body: Center(
            child: CircularProgressIndicator(),
          ),
        );
      },
    );
  }
}
